DO $$ BEGIN

    CREATE TABLE IF NOT EXISTS public.paragraphs ();

    ALTER TABLE public.paragraphs
        ADD IF NOT EXISTS id UUID NOT NULL PRIMARY KEY,
        ADD IF NOT EXISTS ts_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ADD IF NOT EXISTS ts_updated TIMESTAMP WITH TIME ZONE,
        ADD IF NOT EXISTS text TEXT;

END $$
