services:
  api:
    build:
      context: ./api
      target: debug
    develop:
      watch:
        - action: rebuild
          path: ./api/migrations
        - action: rebuild
          path: ./api/src
        - action: rebuild
          path: ./api/Cargo.toml
    environment:
      # RUST_LOG: "debug"
      # RUST_BACKTRACE: "1"
      DB_HOST: "host.docker.internal"
    ports:
      - 3002:3002
    depends_on:
      db:
        condition: service_healthy

  web-app:
    build: ./web-app
    ports:
      - 3000:3000

  db:
    image: postgres
    user: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /var/uhm/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
