DO $$ BEGIN

    -- Table: products

    CREATE TABLE IF NOT EXISTS public.products ();

    ALTER TABLE public.products
        ADD IF NOT EXISTS id UUID NOT NULL PRIMARY KEY,
        ADD IF NOT EXISTS ts_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ADD IF NOT EXISTS ts_updated TIMESTAMP WITH TIME ZONE,
        ADD IF NOT EXISTS name VARCHAR(256) NOT NULL;

END $$
